### ISSUE TITLE
Grouped bug report from using most features

### ISSUE THREAD

**Issue by dewinterjack** [Aayush9029/Khula-Site#7]
Loving the app 💯 
I sent in a feature request and mentioned I would be trying the app out more, here is a list of issues that I encountered:

Opening media controls and trying to use for first time is unresponsive until a window comes up on mac asking for permissions. The iOS app should indicate this will happen.

 This seems to be the case for many features. The message should just indicate that it is happening. Right now it just shows: Done, quick action sent.

---

I got disconnected and was not made aware until I tried to do more commands. No pop up on mac or iOS. I see the option to enable the notification. It looks like the dev didnt want the typical pop up when first opening an app to do with notifications. Maybe a welcome page with this information would be a good idea?

I just got disconnected after the app requiring a restart after changing the screenshot permission. I did not get a notification after enabling the setting local notification.

---

Add option to always allow connections from particular device so mac pop up doesn’t appear.

---

Have an indicator in the menu bar to show if connection is active or not. Like the iOS app has.

---

Hide/Show desktop icons got into the opposite state when triggering from an app and not showing desktop

---

Lock does not actually lock the mac it just turns screen off or does some kind of sleep as the music stops

---

On screen capture > Toggle Desktop Icons and also in Quick Actions > Hide/Show Desktop Icons

These are the same thing, they should have the same name and icon.

**Comment by Aayush9029** [comment]
I'm glad you like the app! Thanks for the amazing feedback! UI / UX improvements you've mentioned have been fixed locally will be released later this spring along side other features.

---

I didn't want to bloat the macOS app too much (send constant requests to iOS app),  I'll consider adding a "check connection in time interval" toggle of some sort! 

---

As for iOS if you enable notifications app will ~~should~~ notify you when you disconnect from the macOS app, as a fail safe pop over turns red when you perform an action. (However As per your request I'll consider implementing a better alert on app open for iOS app)

---

Always allow for "trusted" connection is definitely on my to-do list... 

I Am considering publishing two different macOS apps! One that uses web sockets and other which uses multiplier framework!

>Note: I might make this a toggle (use sockets or multiplier)

---

P.S Again thanks for the amazing feedback ❤️ I'll look over it once more to see if I am missing something!
Personally, I've been using khula a lot in conjunction with  the new Universal Control feature for macOS *12.3 beta* and am excited to add new features and fix issues!

**Comment by Aayush9029** [comment]
@dewinterjack  I've implemented auto join! 🥳 

You won't need to accept every single time!

Set to release in May! Along side other bug fixes you've mentioned and features!
